name: benchmark
seed: 0

model_id: null
save_model: true
save_summary: true

# Output directory for results
hydra:
  run:
    dir: results/${name}/${now:%Y-%m-%d_%H-%M-%S}/local
  sweep:
    dir: results/${name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

defaults:
  - _self_
  - method: npe
  - task: simple1dstationary
  - eval: c2st
  - launcher: slurm
  - partition: none
  - sweeper: none
