
backend: torch
name: 'npe_summary'
device: cpu 
subseq_data_augmentation_fraction: 1.
params_train:
  training_batch_size: 1000
  learning_rate: 1e-3
  validation_fraction: 0.1
  stop_after_epochs: 20
  max_num_epochs: 2147483647
  clip_max_norm: 5.
params_build_posterior:
  sample_with: 'direct'
params_init:
  density_estimator: 'nsf'



defaults:
  - neural_net: rnn_embedding
  - sampler: direct
